dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install poetry
  - poetry install

script:
   - poetry run mypy slack_primitive_cli
   - poetry run flake8 slack_primitive_cli
branches:
  only:
  - master
